---
title: "Partitioning Documentation"
author: "Sophia, Werner, Julian"
date: "`r Sys.Date()`"
output:
  html_document:
    number_sections: true
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introduction
Werner

## Partitioning
Werner

## Motivation
Werner

# Model development

## Simile
Sophia

## R

In addition to the Simile models, we have also created the same models in R again.
These have the same model components and also the same input values as the models in Simile.
Our main motivation behind the R models was to avoid the very time-consuming drawing of the organ fractions.
By using R, we could read the data directly from the table and were not dependent on an intermediate medium such as the Simile graphs.
While Simile is operated entirely via a graphical user interface, our R model is based purely on a line-based script.
This made it sometimes difficult to keep an overview, because the characteristic components of Simile were not directly visible in the R code. Nevertheless, the model is also based on factors, compartments and flows that have to be defined at the beginning.
Here the numeric() function is useful to create vectors for the variables that change during the simulation.
For each of these variables, a vector is created with the length of the planned timesteps.
These vectors are then exchanged with the newly calculated data points during the simulation.
For constant factors, variables are defined with the corresponding constant value at the beginning.
For compartment variables, the first digit in the associated vector is overwritten with the start value of the compartment from Simile.

After all model variables have been defined and prepared, the actual calculation of the model can begin.
This works via a loop with a number of repetitions that corresponds to the desired timesteps of the simulation.
Within the loop are the actual calculations of the model, which are performed one after the other, building on each other.
It is important to keep to the correct order for the calculation of the individual variables, so that variables that are later calculated in the loop are not part of earlier calculations for other variables.
The calculations and also the updating of the individual vectors are strongly based on indexing.
In the current iteration (n), the values of the previous iteration (n-1) are exchanged with the newly calculated value.
The formulas used in R are very similar to those in the Simile Model and only the syntax for if and else conditions had to be adapted.
To calculate the compartments as in Simile, the flow rates at the end of each iteration are added to their corresponding variable, e.g. W[n] <- dW[n-1] + W[n-1], and taken as the basis for the next iteration.
After the last iteration has run, all the desired vectors can be merged into one data frame, which can then be used in different ways.

The implementation of the fractions directly from the table is one of the main differences to the simile models.
The mechanism behind this can be divided into two steps.
In the first step, the relevant fractions are filtered out of the entire table.
The filter is based on the input in the model function where the desired crop can be specified.
The default input is wheat, for which we have also drawn the fractions in Simile.
In the second step, the data from the filtered table is used to interpolate a value that corresponds to the respective DVS value.
For this, the approx() function was a great help, as it is able to interpolate for a value within a dataframe.

Our goal for the R models was to achieve results as close as possible to our simile results.
In principle, the visible calculations of both models are the same, but nevertheless there are slight deviations.
One influencing factor here is the different rounding of the two programmes.
Even if the same numbers are displayed on the surface, it is possible that other numbers are calculated internally.

We have written a very simple function with which we can examine the results of two data frames and their difference.
We found that the difference was smallest for the no_partitioning model and increased for the more complex models.
A second source for differences between the models are also slight inaccuracies when drawing in Simile.
To examine the differences between the two models more closely, there would have been another possibility.
Simile allows to export the drawn graphs as a .csv table.
These could then have been used as input in the R model for the fractions.
The R model would still have interpolated from this data, but anomalies in the drawn data would have been represented.

- Possible extensions
  - probabilistic uncertainty
  - Monte Carlo simulation
  - Mehr Änderungen im Funktionsinput
- nice backup by inline code

## List of variables
Julian

## Partitioning Fractions
Wie haben die Lintul Menschen diese Fractions bekommen?

# Results

## Without Partitioning
Julian

## Partitioning
Julian

## Partitioning Other Crops
Julian

## Partitioning TRANRF
Sophia

# Simplifications of the model
Sophia

# Conclusion
Sophia

# Outlook
Sophia




